TRUTH = [
    "What is your idea of a perfect date? 🌹",
    "Describe your dream romantic getaway. ✈️",
    "What's the most romantic gesture you've ever made for someone? 💖",
    "Have you ever been in love at first sight? 👀",
    "What's your favorite love song and why? 🎵",
    "Share a romantic movie that has deeply impacted you. 🎬",
    "Have you ever written a love letter? ✉️", "Describe your perfect kiss. 💋",
    "Who was your first crush and what attracted you to them? 💘",
    "What's your idea of the perfect romantic evening? 🌙",
    "Have you ever had a secret admirer? 💌",
    "What is your favorite memory with a past partner? 📆",
    "Name a celebrity couple you admire and why. 👫",
    "If you could go on a romantic date anywhere in the world, where would it be? 🗺️",
    "Have you ever been serenaded or serenaded someone? 🎶",
    "Share a romantic tradition you'd like to start with a partner. 🕯️",
    "What's your ultimate romantic fantasy? 🔥",
    "Describe your most memorable kiss. 💏",
    "Have you ever experienced love at the wrong time or place? ⌛️",
    "What's your favorite romantic gesture to receive? 🎁",
    "Share a romantic quote that resonates with you. 💬",
    "What's your love language - words of affirmation, acts of service, receiving gifts, quality time, or physical touch? 💬🎁⏰👩‍❤️‍👨",
    "Describe your ideal proposal scenario. 💍",
    "What's your outlook on public displays of affection? 🙈",
    "Have you ever been surprised with a romantic gesture, and what was it? 🎈",
    "Name a romantic book that has left a lasting impression on you. 📚",
    "What's the most romantic meal you've ever had? 🍽️",
    "If you could experience a fictional love story, which one would it be and why? 💓",
    "What's your favorite thing about falling in love? 🥰",
    "Describe the most romantic setting you've ever been in. 🏞️",
    "Share an intimate piece of artwork or poem that speaks to your romantic side. 🖼️📝",
    "Describe the feeling of butterflies in your stomach when you're in love. 🦋",
    "Have you ever danced under the stars with someone you love? 💃🕺",
    "What's your idea of the perfect romantic gift? 🎁",
    "Have you ever written a poem or song about love? 🎶📝",
    "Share an unforgettable romantic moment you've experienced. 🌠",
    "What's your favorite romantic tradition from a different culture? 🌍",
    "Have you ever stargazed with a loved one? 🌌",
    "If you could relive a romantic memory, which one would it be? ↩️",
    "What's the most thoughtful surprise you've planned for someone you love? 🎁",
    "Share a meaningful love-related lesson you've learned. 📚",
    "What are your thoughts on long-distance relationships? 🌎",
    "Describe your ideal way to spend Valentine's Day. 💝",
    "Have you ever had a profound romantic experience while traveling? 🌍",
    "What's your favorite romantic line from a movie or book? 🎬📖",
    "Share a romantic gesture you've always wanted to experience. 🌷",
    "Describe a romantic moment from your favorite childhood memory. 🧸",
    "Have you ever received a love note or written one to someone? 📝",
    "What's the most unexpected romantic encounter you've had? 🎉",
    "If you could create your own romantic holiday, how would you celebrate it? 🎉",
    "🍕 What's the most embarrassing thing your parents have caught you doing?",
    "🎤 Have you ever lip-synced in front of the mirror pretending to be a famous singer?",
    "📸 Have you ever taken a selfie you immediately deleted because you didn't like how you looked?",
    "🐶 What's the silliest name you've ever given a pet?",
    "🎬 What movie makes you cry no matter how many times you watch it?",
    "🎮 Have you ever pretended to be sick to stay home and play video games?",
    "💃 What's the most embarrassing dance move you've ever done in public?",
    "📚 Have you ever cheated on a test?",
    "🎁 What's the worst gift you have ever received?",
    "🤔 Have you ever pretended to be on the phone to avoid talking to someone?",
    "🍨 What's your favorite ice cream flavor?",
    "📺 Have you ever binge-watched a TV show in one day?",
    "🌃 What's the scariest movie you've ever watched?",
    "🎧 What's your go-to karaoke song?",
    "🎁 What's the best gift you have ever received?",
    "🤐 What's the most trouble you've ever gotten into at school?",
    "🏠 If you could live anywhere in the world, where would it be?",
    "🎒 What's the most embarrassing thing that's happened to you at school?",
    "🍔 If you could only eat one food for the rest of your life, what would it be?",
    "🛌 What's the weirdest place you've ever fallen asleep?",
    "💭 What's the silliest dream you've ever had?",
    "🐛 Have you ever eaten something off the floor?",
    "🏈 What's the most embarrassing sports moment you've had?",
    "🎭 Have you ever pretended to be sick to get out of something you didn't want to do?",
    "🌞 What's your favorite thing to do on a sunny day?",
    "📷 What's the most embarrassing photo on your phone?",
    "📚 What's your favorite subject in school and why?",
    "📱 What's the last text message you received and from whom?",
    "🌼 Do you have a favorite flower, and if so, what is it?",
    "🤭 What's the funniest thing that's ever happened to you in public?",
    "🏓 Have you ever pretended to know more about a topic than you actually do?",
    "🗺️ If you could travel anywhere in the world, where would you go first?",
    "🤬 What's the last thing that made you angry?",
    "🌮 If you could only eat one type of cuisine for the rest of your life, what would it be?",
    "📚 What's the last book you've read and would you recommend it?",
    "🎨 Have you ever drawn on something you weren't supposed to?",
    "🚗 What's the scariest experience you've had while driving or being in a car?",
    "🎥 What's your favorite movie quote and why?",
    "🤝 What's the nicest thing someone has ever done for you?",
    "👚 What's your favorite piece of clothing that you own?",
    "🎂 What's the best birthday present you've ever received?",
    "🧐 Have you ever stalked someone on social media?",
    "📖 What's your favorite childhood book?",
    "🎶 What song do you currently have on repeat?",
    "📝 Have you ever written a love letter or a secret admirer note?",
    "👣 What's the farthest you've ever walked in one day?",
    "🕶️ What's the most embarrassing fashion trend you've ever tried?",
    "🤣 What's the funniest nickname you've ever been given?",
    "📺 What's your guilty pleasure TV show?",
    "🎉 What's one thing you want to accomplish before the end of the year?",
    "🙈 What's the most embarrassing thing that's happened to you at school?",
    "📝 Have you ever cheated on a test?",
    "🤪 What's the silliest thing you've ever done to impress a crush?",
    "🤒 Have you ever pretended to be sick to get out of something?",
    "💭 What's the weirdest dream you've ever had?",
    "👀 Have you ever stalked someone on social media?",
    "😳 What's your most embarrassing screen name or username?",
    "🤥 Have you ever lied to your parents about where you were going?",
    "👮‍♂️ What's the most trouble you've ever gotten into at school?",
    "🤢 What's the grossest food you've ever eaten?",
    "📲 Have you ever accidentally sent a text to the wrong person?",
    "🚿 What's the longest you've ever gone without showering?",
    "🙊 What's a bad habit you have that you try to hide?",
    "🏃‍♂️ Have you ever snuck out of the house?",
    "👨‍👩‍👧 What's the most embarrassing thing your parents have caught you doing?",
    "🍎 Have you ever had a crush on a teacher?",
    "😭 What's the most ridiculous thing you've ever cried about?",
    "🤷‍♂️ Have you ever broken something and blamed someone else?",
    "👬 What's the most trouble you've ever gotten into with your friends?",
    "🛍️ Have you ever shoplifted?",
    "🤔 What's the weirdest thing you've ever Googled?",
    "👂 Have you ever eavesdropped on someone's conversation?",
    "📷 What's the most embarrassing thing you've posted on social media?",
    "🍽️ Have you ever dined and dashed at a restaurant?",
    "😬 What's the most embarrassing thing you've done to impress someone you liked?",
    "🏊‍♂️ Have you ever peed in a pool?",
    "👗 What's the most embarrassing thing you've worn in public?",
    "❤️ Have you ever told someone you love them when you didn't mean it?",
    "🤥 What's the worst lie you've ever told your best friend?",
    "📖 Have you ever read someone's diary or journal without permission?",
    "😳 What's the most embarrassing thing you've ever done in front of your crush?",
    "😍 Have you ever had a crush on a friend's sibling?",
    "😳 What's the most embarrassing nickname you've ever been given?",
    "🗣️ Have you ever spread a rumor that wasn't true?",
    "😳 What's the most embarrassing thing you've ever said to someone you liked?",
    "😴 Have you ever fallen asleep in class?",
    "👨‍👩‍👧‍👦 What's the most embarrassing thing your parents have done in front of your friends?",
    "💨 Have you ever farted in an elevator and blamed someone else?",
    "🎉 What's the most embarrassing thing you've done at a party?",
    "🎁 Have you ever regifted a present?",
    "🚽 What's the most embarrassing thing you've ever done in a public restroom?",
    "🤥 Have you ever pretended to know something you didn't just to impress someone?",
    "🎂 What's the most embarrassing thing that's ever happened to you at a birthday party?",
    "😂 Have you ever laughed at something serious?",
    "⚽️ What's the most embarrassing thing that's ever happened to you while playing a sport?",
    "🏠 Have you ever pretended not to be home when someone knocked on your door?",
    "👕 What's the most embarrassing thing you've ever worn to school?",
    "🤦‍♂️ Have you ever had a wardrobe malfunction in public?",
    "🙏 What's the most embarrassing thing you've ever confessed to a priest or religious leader?",
    "🎁 Have you ever pretended to like a gift you hated?",
    "🌟 What's your biggest fear?",
    "🌈 Share a childhood memory that makes you smile.",
    "🎵 What's your go-to karaoke song?",
    "📚 Name a book that changed your life.",
    "🎭 If you could be any fictional character, who would you be?",
    "🌍 What's your dream travel destination?",
    "🎨 Share a piece of art that speaks to you.",
    "🍔 What's your favorite comfort food?",
    "💃 Describe your ideal dance party.",
    "🛌 What's your most embarrassing moment?",
    "🌻 Share something that never fails to make you happy.",
    "🚀 If you could have any superpower, what would it be?",
    "🏰 Name a place you'd love to visit but haven't yet.",
    "🚲 What's your favorite way to stay active?",
    "🎸 Share a song that holds special meaning for you.",
    "🎬 If your life were a movie, what genre would it be?",
    "🍣 Describe your perfect meal.", "🌺 What's your favorite flower and why?",
    "📺 Share a TV show you could watch on repeat.",
    "🌴 Describe your ideal vacation.",
    "🍦 What's your favorite ice cream flavor?",
    "🌄 Share a sunset that took your breath away.",
    "📖 Name a quote that inspires you.",
    "🏆 What's your biggest accomplishment so far?",
    "🚗 Your dream car - what is it like?",
    "🎢 What's your favorite amusement park ride?",
    "⛺️ Describe your perfect camping trip.",
    "🌠 Share a dream you remember vividly.",
    "🏈 What's your favorite sports memory?",
    "🍹 If your life were a cocktail, what would it be called?",
    "🌞 Describe your perfect day from start to finish.",
    "⏳ Share a moment when time stood still for you.",
    "🎁 What's the best gift you've ever received?",
    "🌍 If you could live anywhere in the world, where would it be?",
    "📷 Share a special photo and its story.",
    "🍻 What's your favorite beverage to unwind with?",
    "🌼 What's your favorite scent and why?", "🎁 What's your love language?",
    "👑 If you were royalty, what would your title be?",
    "🌇 Share a city skyline that mesmerized you.",
    "🚤 Describe your perfect day on the water.",
    "🌈 What's the most beautiful natural phenomenon you've witnessed?",
    "💎 Share a valuable life lesson you've learned.",
    "🏝 Describe your dream island getaway.",
    "🏰 If you had a castle, what would it look like?",
    "💼 Share a career milestone that made you proud.",
    "🎉 What's your favorite way to celebrate a special occasion?",
    "🚀 If you could visit space, would you go?",
    "🎡 Share a carnival or fair memory that makes you smile.",
    "🎯 What's your biggest goal for the future?",
    "Describe your wildest fantasy in detail. 🌟😏",
    "What is your favorite position and why? 😜",
    "Have you ever been attracted to a friend's partner? 😳",
    "Share your most embarrassing bedroom moment. 🙈",
    "What's the longest intimate session you've ever had? ⏱️😉",
    "Have you ever used a toy in the bedroom? 🍆😉",
    "Describe your last hookup in graphic detail. 💋😏",
    "Share a sexy selfie from your phone. 📸😘",
    "What's your idea of a perfect date night? 🌹🕯️",
    "Have you ever had a one-night stand? 😮",
    "Describe your ultimate turn-on. 🔥😍",
    "What's the most adventurous place you've been intimate? 🌴🏞️",
    "Share your most forbidden desire. 💭😈",
    "If you could have a threesome with any two people, who would they be? 👩‍❤️‍💋‍👨😉",
    "What's your go-to move in the bedroom? 🛌💃",
    "Have you ever fantasized about someone in this room? 😏😉",
    "Share your darkest secret. 🤫😈",
    "What's the most unusual place you've watched adult content? 📺🙈",
    "If you could choose any celebrity to sleep with, who would it be? 🌟😍",
    "Share your most seductive dance move. 💃😘",
    "What's the sexiest feature of the person to your left? 👀😏",
    "What's the most intimate text you've ever received? 📱😉",
    "Share your favorite role-playing scenario. 👮‍♀️👩‍⚕️",
    "Have you ever sent a suggestive message to the wrong person? 📬😳",
    "Rate everyone in the room from most to least attractive. 💯😏",
    "What's the naughtiest thing you've ever done in public? 🙊😉",
    "Describe your ideal partner in detail. 💑😍",
    "Have you ever been caught in the act? 🙈😳",
    "Share your most sensual memory. 🌹😘",
    "What's your biggest turn-off in a partner? 🤨🔕",
    "Say your favorite dirty word in different accents. 🤐🗣️",
    "Share your most unforgettable intimate experience. 💫😉",
    "Who in the room do you think would be the best kisser? 💋😏",
    "Have you ever used food in the bedroom? 🍓🍫",
    "What's your guilty pleasure in the bedroom? 🙊😉",
    "Share the most memorable pick-up line you've used. 😏🔥",
    "What's your favorite part of the body? 👀😍",
    "If you could erase an ex from your memory, who would it be? 🧠🙅‍♂️",
    "What's your ultimate deal-breaker in a relationship? ❌🙅‍♀️",
    "Share your hottest dream. 💭😈",
    "Have you ever been walked in on during an intimate moment? 🚪😳",
    "What's the most arousing text you've ever sent? 📱😉",
    "Tell us about your first intimate experience. 🌹🙈",
    "Share a seductive line using only emojis. 💬😏",
    "What's your secret talent in the bedroom? 🎭😉",
    "Have you ever had a crush on a teacher? 👩‍🏫😏",
    "Describe the most sensual touch you've ever experienced. ✋😘",
    "Who in the room do you think has the wildest fantasies? 🤔🌪️",
    "Share the most daring outfit you've worn. 👗😉",
    "What's your ultimate turn-off in the bedroom? 🚫🤷‍♂️",
    "Describe your wildest fantasy in explicit detail. 😳🔥",
    "What's the most adventurous place you've had intimate relations? 🌴😏",
    "Share your most embarrassing bedroom moment. 🙈😅",
    "Have you ever used adult toys, and if so, which ones? 🍆😉",
    "Confess your favorite adult movie or website. 🎥😈",
    "Tell us about a naughty dream you've had recently. 💭😜",
    "Have you ever role-played in the bedroom, and what was the scenario? 👮‍♂️👩‍⚕️",
    "Share a sexy text message you've sent or received. 📱🔞",
    "What's your secret turn-on that would surprise everyone? 🤫💦",
    "Describe your ideal romantic evening with your partner. 🍷💑",
    "Have you ever been caught in the act? Tell us about it! 🙊😳",
    "What's the most taboo thing that turns you on? 🚫😍",
    "Share a sensual fantasy you've never told anyone about. 🌌😉",
    "Do you have a favorite adult game, and what is it? 🃏🎲",
    "Tell us about a time you experimented with something new in the bedroom. 👩‍❤️‍👨🔬",
    "Describe your sexiest outfit and what makes it so alluring. 👗✨",
    "Share a secret desire you've never acted upon. 🔒💭",
    "Confess the most daring thing you've done in the name of love. 🤔❤️",
    "What's your guilty pleasure when it comes to romance? 🍫🥂",
    "Describe your most memorable kiss, and with whom. 💋😍",
    "Who is your ultimate celebrity crush and why? 🌟😘",
    "Share a sensual massage technique you enjoy. 💆‍♂️💆‍♀️",
    "What's your go-to move for initiating intimacy? 🚪😏",
    "Tell us about a time you surprised someone with a romantic gesture. 🎁💖",
    "What part of your body do you consider your most erogenous zone? 🤫🔥",
    "Confess the most unusual place you've been intimate with someone. 🚪🙊",
    "What's your favorite role in the bedroom - dominant or submissive? 👠💪",
    "Share a sensual fantasy that involves food. 🍓🍫",
    "What's your most scandalous online dating experience? 💻😉",
    "Describe your wildest position or technique that brings you the most pleasure. 🔄😌",
    "If you could fulfill any fantasy, what would it be? 💭🔓",
    "Share a passionate encounter you still dream about. 💭😍",
    "What's your favorite way to set the mood before getting intimate? 🕯️🎶",
    "Have you ever been caught watching adult content? Tell us about it! 👀📺",
    "Confess a fetish or kink that you've always been curious about. 👢🍏",
    "Call a past partner and tell them one thing you wish you had done differently. 📞😳",
    "Share an adult-related dare you've completed in the past. 🎯😏",
    "If you had to pick one adult performer to star with in a film, who would it be? 🎬😉",
    "What's your secret pleasure that you've never shared with anyone? 🤫😉",
    "Describe your preferred environment for intimate moments - soft lights, candles, music, or something else? 🕯️🎵",
    "Tell us about a time you surprised someone with a sensual gift. 🎁💋",
    "If you could have a romantic encounter with any historical figure, who would it be? 🏛️😘",
    "Confess the most impulsive decision you've made in the name of romance. 😬❤️",
    "Share a memorable taboo experience that challenged your boundaries. 🚫😳",
    "Describe your most unusual turn-on. 🤔🔥",
    "What's your favorite memory from a past relationship? 💭❤️",
    "Share a guilty pleasure adult film or book that you secretly enjoy. 📚🍿",
    "Confess a naughty habit no one would expect from you. 😈🤫",
    "If you could erase one of your past romantic experiences, which would it be? 🧹🤔",
    "What's your ultimate bedroom fantasy involving two other people? 👩‍❤️‍💋‍👨🔥"
]

DARE = [
    "🌹 Send me a voice message saying 'I Love You' in the most romantic way!",
    "😘 Write me a love letter and send it to my inbox.",
    "💃 Dance to a romantic song and send me a video of it.",
    "📸 Take a selfie blowing me a kiss and send it to me.",
    "🎶 Sing a love song and share the video with me.",
    "📞 Call me and describe your perfect date with me.",
    "💋 Send me a video of you blowing me a kiss.",
    "💌 Write me a poem and read it to me over a video call.",
    "🍫 Treat me to a virtual dessert date and chat about our sweetest memories.",
    "🚗 Plan our dream road trip and share the itinerary with me.",
    "🌅 Send me a view of the sunset and tell me what it reminds you of.",
    "🍕 Choose my next pizza topping and we'll order it together.",
    "🌠 Name a star after me and send me the certificate.",
    "👀 Send me a video of you making heart shapes with your hands.",
    "📖 Read me a chapter from your favorite love story.",
    "🎨 Paint or draw a picture of us together and share it with me.",
    "🚴 Describe a thrilling adventure date and let's plan it together.",
    "🏖️ Share a list of romantic destinations you'd like to visit with me.",
    "🌺 Create a bouquet using virtual flowers and send it to me.",
    "🎬 Act out a romantic movie scene and record it for me.",
    "🧁 Bake me a virtual cupcake and write a sweet message on it.",
    "🕯️ Light a candle and tell me what your ideal date night looks like.",
    "🥂 Plan our perfect virtual dinner date and send me the menu.",
    "🚀 Describe a futuristic date idea and how it would play out.",
    "🌌 Share a stargazing spot and let's imagine being there together.",
    "🛀 Create a bubble bath playlist for me to relax to.",
    "💃 Describe your dream dance under the stars and let's choose a song for it.",
    "🍿 Plan a movie night and share the top romantic movies you want to watch.",
    "💬 Use emojis to describe your feelings for me right now.",
    "🛌 Share your ideal cuddle position and why you like it.",
    "✈️ Design our dream vacation together and share the details with me.",
    "🎤 Sing a duet with me, each recording a part and mixing it together.",
    "💭 Describe a reimagined fairy-tale ending for us and share it with me.",
    "🚁 Plan a virtual helicopter ride and describe the scenery to me.",
    "🎮 Describe a video game adventure you'd like to conquer with me.",
    "🚢 Plan a romantic cruise and share the activities you'd like us to do.",
    "📼 Send me a clip of your favorite romantic movie scene and explain why you love it.",
    "🌾 Name a romantic spot in nature and describe what we'd do there.",
    "🏰 Design our dream castle and tell me which room is your favorite.",
    "📝 Write down three things you love about me and share it with me.",
    "💡 Describe your idea of a perfect proposal and how you'd make it special.",
    "🍧 Plan a virtual ice cream date and tell me your top three flavors.",
    "🌋 Share a list of adventures we should conquer together and why.",
    "🚂 Plan a scenic train journey and let's pick the best seat together.",
    "🍝 Cook a virtual dinner for me and describe how you'd make it romantic.",
    "🎸 Plan a virtual karaoke night and pick a romantic duet for us to sing.",
    "🗺️ Pin a map with all the places you want to explore with me.",
    "🎁 Plan a surprise gift for me and drop hints about what it could be.",
    "🥑 Name a romantic dish you'd like to cook for me and describe it in detail.",
    "🕰️ Share a romantic storyline of our future together and how it unfolds.",
    "🍸 Send a suggestive text to someone in your contact list.",
    "📸 Take a sultry selfie and send it to the group chat.",
    "💋 Seductively lick your lips for 30 seconds.",
    "🎵 Perform a strip tease to your favorite song.",
    "🍒 Use ice cubes to sensually trace your partner's body.",
    "🔥 Share a dirty secret you've never told anyone.",
    "🍷 Take a shot without using your hands.",
    "📝 Write a naughty fantasy and read it out loud.",
    "🍑 Show off your best twerking moves for a minute.",
    "💬 Describe your wildest sexual encounter in detail.",
    "📞 Call an ex and flirt with them for 2 minutes.",
    "🤫 Share your most intimate craving with the group.",
    "💦 Send a voice message moaning your favorite fantasy.",
    "🚿 Take a shower fully clothed and share a photo.",
    "🍭 Use a dirty pickup line on the person next to you.",
    "📱 Exchange phones with someone for 2 minutes.",
    "💄 Apply lipstick using only your mouth.",
    "🎲 Roll the dice and perform an action for that number of minutes.",
    "🍌 Seductively eat a piece of fruit in front of everyone.",
    "🖼️ Draw a sensual sketch of someone in the room.",
    "📼 Mimic a romantic movie scene with someone.",
    "🔓 Share a secret kink or fetish with the group.",
    "🕯️ Perform a sensual dance with a lit candle in hand.",
    "🍬 Suck on a lollipop for 1 minute seductively.",
    "💭 Whisper your favorite sexual position in someone's ear.",
    "👅 Lick whipped cream off someone's body.",
    "🔐 Share a passionate kiss with someone in the group.",
    "🎤 Sing a sexy song with extra flair and passion.",
    "🍯 Use honey to write your crush's name on your body.",
    "💌 Compose and send a steamy haiku to the group.",
    "💪 Perform a burlesque-inspired workout routine.",
    "🖥️ Share the sexiest photo you have on your phone.",
    "🍡 Feed someone a piece of food with your mouth only.",
    "💬 Whispers dirty talk in someone's ear for 1 minute.",
    "🚪Go kiss the first person you see outside the door.",
    "👀 Perform a seductive eye contact challenge for 30 seconds.",
    "🍦Take a sensuous bite of ice cream and moan with pleasure.",
    "🌹Give a lap dance to someone in the room.",
    "💝Give everyone a flirtatious compliment.",
    "🛏️Describe your favorite sexual fantasy in vivid detail.",
    "💄Apply lipstick with your non-dominant hand.",
    "🍸Create a cocktail with a suggestive name and ingredients.",
    "💋Kiss the person on your right for 10 seconds.",
    "📞Text a random number a flirty message.",
    "🕰️Act out your flirtiest role-play scenario.",
    "🍾Open a bottle of champagne with a seductive pop.",
    "💬Describe your most memorable intimate moment.",
    "🔑Wear a handcuff for the next 3 rounds.",
    "🎥Act out a seductive scene from a movie.",
    "📱Send a risky photo to someone in your contact list.",
    "Give someone a piggyback ride around the room 🏃‍♂️",
    "Sing a song in a funny voice 🎤", "Do a handstand against the wall 🤸‍♂️",
    "Do 10 jumping jacks 💪", "Tell a joke and make everyone laugh 😂",
    "Dance like nobody's watching 💃",
    "Recite a tongue twister three times fast 🤪", "Do the chicken dance 🐔",
    "Mime your favorite hobby 🎨",
    "Give a compliment to everyone in the room 🌟",
    "Act out a scene from a movie 🎬",
    "Do your best impression of a celebrity 😎",
    "Recite the alphabet backward 🅰️🔠",
    "Recreate a famous painting or sculpture 🖼️",
    "Balance a spoon on your nose 🥄", "Do a cartwheel 🤸‍♀️",
    "Tell a funny story from your childhood 🤣", "Do the Macarena 💃",
    "Speak in a different accent for the next 5 minutes 🗣️",
    "Take a silly selfie with a prop 📸", "Recite a poem in a dramatic voice 📜",
    "Do a hand puppet show 🖐️🦁",
    "Tell a riddle and make others guess the answer 🤔",
    "Perform a magic trick 🎩✨", "Do a 1-minute plank exercise 🕐",
    "Recreate a famous movie scene 🎥",
    "Perform a random act of kindness for someone else 🌈",
    "Attempt to breakdance 🕺", "Recite a nursery rhyme with gestures 🎶",
    "Strike a pose and hold it for 30 seconds 🕺",
    "Act like your favorite animal 🐶",
    "Recite a tongue twister without stumbling 🗣️", "Do a somersault 🤸",
    "Tell a funny joke and make everyone laugh 😄",
    "Do your best robot dance 🤖", "Mimic a famous landmark or monument 🗽",
    "Skip around the room 🏃‍♂️", "Recreate a famous meme or viral video 🎥",
    "Do the cha-cha slide 💃",
    "Tell a scary story in the dark with a flashlight 🕯️",
    "Recreate a famous painting 🎨", "Perform a silly walk like Monty Python 🚶",
    "Tell a funny knock-knock joke 🚪😂", "Do a backflip 🤸‍♂️",
    "Recite a tongue twister with a mouth full of water 🚰",
    "Perform a dramatic reading of a menu 💬",
    "Try to juggle three objects 🤹‍♂️",
    "Recite a famous speech in a funny voice 🗣️",
    "Spin around 10 times and then try to walk in a straight line 🌀",
    "Tell a funny story using only emojis 😄📖",
    "Send a flirty text to the third person in your contact list 💋",
    "Whisper something dirty in the ear of the player on your left 👂😏",
    "Take a body shot off the person next to you 🥃👄",
    "Show the last message you received on your phone 📱",
    "Send a suggestive selfie to the group chat 📸😉",
    "Kiss the neck of the person across from you 💏",
    "Give a lap dance to the player of your choice 💃🕺",
    "Let someone give you a sensual massage for 2 minutes 💆‍♂️💆‍♀️",
    "Share your most embarrassing hookup story 😳🛌",
    "Go commando for the next 3 rounds 😮🩲",
    "Share your wildest fantasy with the group 🌟😈",
    "Make out with a pillow as if it were your crush 😗🛏️",
    "Seductively eat a piece of fruit 🍓🔥",
    "Give the person to your right a seductive stare for 30 seconds 👀😍",
    "Write a secret on someone's body with your tongue 🤫👅",
    "Show the group your best strip tease 👯‍♂️👯‍♀️",
    "Demonstrate your favorite sex position with a chair 🪑😏",
    "Perform a seductive dance to a slow song 🎶💃",
    "Rate everyone in the room on a scale of 1 to 10 📊😉",
    "Secretly remove an article of clothing and see if anyone notices 🤫👗",
    "Recreate a romantic movie scene with a fellow player 🎬❤️",
    "Tell the most arousing story from your experience 🔥📖",
    "Share your wildest sexual encounter in detail 🛌😉",
    "Put on lipstick without using your hands 💄👄",
    "Recite a provocative poem to the group 📜😏",
    "Blindfold yourself and let someone tease you for a minute 🙈😉",
    "Share the dirtiest text you've ever received 📲😈",
    "Give a tantalizing lap dance to the player across from you 💋🕺",
    "Describe your ideal partner's attributes in explicit detail 🥵💭",
    "Give a foot massage to the person of your choice 👣😌",
    "Sensually feed a piece of chocolate to someone with your mouth 🍫😏",
    "Act out a steamy scene from a famous romance novel 📚😘",
    "Reenact your favorite scene from an adult movie 🎞️😉",
    "Play a sexy song and dance provocatively for 1 minute 🎵💃",
    "Share an intimate moment that you've never told anyone about 🤫😉",
    "Show off your sexiest dance moves to the group 💃🕺",
    "Write a sensual haiku about the person on your right 📝😘",
    "Seductively eat a banana 🍌😉",
    "Share the naughtiest thing you've done in a public place 🤭🏙️",
    "Wink seductively at the person on your left 😉😏",
    "Recreate a steamy scene from a romantic movie 🎥😍",
    "Flirt with the waiter/waitress and get their number 😘📱",
    "Perform a striptease to your favorite sultry song 🎵👯‍♂️",
    "Do a sensual body roll in the center of the room 🔄😘",
    "Share your most vivid dream involving someone in the room 🌌😉",
    "Flaunt your best bedroom eyes to the group 👀😏",
    "Share a juicy secret that you've never told anyone 🤭🔥",
    "Give someone a sexy lap dance with your choice of music 💋💃",
    "Whisper the most seductive thing you can think of in someone's ear 😏👂",
    "Send a sultry text to your crush and let the group read it 📱😉",
    "Send a flirty text to the third person in your contact list 💋",
    "Whisper something dirty in the ear of the player on your left 👂😏",
    "Take a body shot off the person next to you 🥃👄",
    "Show the last message you received on your phone 📱",
    "Send a suggestive selfie to the group chat 📸😉",
    "Kiss the neck of the person across from you 💏",
    "Give a lap dance to the player of your choice 💃🕺",
    "Let someone give you a sensual massage for 2 minutes 💆‍♂️💆‍♀️",
    "Share your most embarrassing hookup story 😳🛌",
    "Go commando for the next 3 rounds 😮🩲",
    "Share your wildest fantasy with the group 🌟😈",
    "Make out with a pillow as if it were your crush 😗🛏️",
    "Seductively eat a piece of fruit 🍓🔥",
    "Give the person to your right a seductive stare for 30 seconds 👀😍",
    "Write a secret on someone's body with your tongue 🤫👅",
    "Show the group your best strip tease 👯‍♂️👯‍♀️",
    "Demonstrate your favorite sex position with a chair 🪑😏",
    "Perform a seductive dance to a slow song 🎶💃",
    "Rate everyone in the room on a scale of 1 to 10 📊😉",
    "Secretly remove an article of clothing and see if anyone notices 🤫👗",
    "Recreate a romantic movie scene with a fellow player 🎬❤️",
    "Tell the most arousing story from your experience 🔥📖",
    "Share your wildest sexual encounter in detail 🛌😉",
    "Put on lipstick without using your hands 💄👄",
    "Recite a provocative poem to the group 📜😏",
    "Blindfold yourself and let someone tease you for a minute 🙈😉",
    "Share the dirtiest text you've ever received 📲😈",
    "Give a tantalizing lap dance to the player across from you 💋🕺",
    "Describe your ideal partner's attributes in explicit detail 🥵💭",
    "Give a foot massage to the person of your choice 👣😌",
    "Sensually feed a piece of chocolate to someone with your mouth 🍫😏",
    "Act out a steamy scene from a famous romance novel 📚😘",
    "Reenact your favorite scene from an adult movie 🎞️😉",
    "Play a sexy song and dance provocatively for 1 minute 🎵💃",
    "Share an intimate moment that you've never told anyone about 🤫😉",
    "Show off your sexiest dance moves to the group 💃🕺",
    "Write a sensual haiku about the person on your right 📝😘",
    "Seductively eat a banana 🍌😉",
    "Share the naughtiest thing you've done in a public place 🤭🏙️",
    "Wink seductively at the person on your left 😉😏",
    "Recreate a steamy scene from a romantic movie 🎥😍",
    "Flirt with the waiter/waitress and get their number 😘📱",
    "Perform a striptease to your favorite sultry song 🎵👯‍♂️",
    "Do a sensual body roll in the center of the room 🔄😘",
    "Share your most vivid dream involving someone in the room 🌌😉",
    "Flaunt your best bedroom eyes to the group 👀😏",
    "Share a juicy secret that you've never told anyone 🤭🔥",
    "Give someone a sexy lap dance with your choice of music 💋💃",
    "Whisper the most seductive thing you can think of in someone's ear 😏👂",
    "Send a sultry text to your crush and let the group read it 📱😉",
    "Send a funny selfie to the third person in your contact list. 🤳",
    "Make a prank call to a friend and try to keep a straight face. 📞😆",
    "Go outside and yell 'I love cookies' at the top of your lungs. 🍪📢",
    "Text your crush and confess your secret admiration for them. 😍📱",
    "Dance wildly for 30 seconds without any music. 💃🕺",
    "Wear your clothes inside out for the next 30 minutes. 👚👖",
    "Sing a song in a foreign language of your choice. 🎤🌍",
    "Call a pizza place and order a burger. 🍕🍔",
    "Write a poem about a household item and share it with the group. ✍️📜",
    "Pretend to be a news anchor reporting on your imaginary pet's adventures. 📰🐶",
    "Recreate a famous meme and share it with the group. 😂📸",
    "Text your parents 'I love broccoli' without any context. 🥦📱",
    "Do your best impression of a celebrity of the group's choice. 🌟🎭",
    "Use a filter and record a 1-minute vlog about your day. 📹😜",
    "Draw a caricature of someone in the group and show it to them. 🎨😄",
    "Speak in an accent of your choice for the next 10 minutes. 🗣️🌍",
    "Eat a spoonful of a condiment of the group's choice (e.g., ketchup, mustard). 🥄🤢",
    "Do an interpretive dance to a randomly chosen song. 💃🕺🎶",
    "Make a creative sandwich using at least five different ingredients. 🥪🧀🥬",
    "Recite a tongue twister three times without making a mistake. 🗣️👅",
    "Tell a joke, and everyone has to laugh even if it’s not funny. 😂🃏",
    "Mimic your favorite cartoon character for 30 seconds. 🤪📺",
    "Do a handstand against a wall and hold it for as long as you can. 🤸‍♂️⏳",
    "Compliment every person in the room with a straight face. 😊👍",
    "Put on a blindfold and try to guess three different food items by taste. 🍴👀",
    "Act out a scene from your favorite movie. 🎬🤠",
    "Wear your shirt as a cape and pretend to be a superhero for the next 10 minutes. 🦸‍♂️👕",
    "Create a funny meme using a photo of someone in the group. 😆📸",
    "Send a DM to a celebrity on social media and share the response with the group. 📩🌟",
    "Take a selfie with an inanimate object and pretend it’s your best friend. 📸🤖",
    "Recite the alphabet backward in less than 30 seconds. 🔤⏪",
    "Draw a funny doodle on your face with washable markers. 🖍️😜",
    "Make a sandwich blindfolded and then eat it without knowing the ingredients. 🥪🙈",
    "Do a 30-second commercial promoting a random object in the room. 📺🛍️",
    "Invent a new dance move and teach it to everyone. 💃🕺",
    "Take a silly photo with a random object in the room and post it on social media. 📸😋",
    "Wink at a random person in the room every time you speak for the next 5 minutes. 😉🗣️",
    "Recreate a famous movie scene using only gestures and expressions. 🎬😯",
    "Create a rap about the host of the game and perform it for the group. 🎤🎶",
    "Balance a spoon on your nose for as long as you can. 🥄👃⏱",
    "Recite a famous quote in a dramatic Shakespearean accent. 🎭🗣️",
    "Propose a toast to the most random object in the room. 🥂🍞",
    "Do a 1-minute stand-up comedy routine about a topic chosen by the group. 😄🎤",
    "Write and perform a short love song about your favorite food. 🎸🍔",
    "Perform a magic trick with a set of playing cards. 🎩🃏",
    "Recreate a famous painting using only items found in the room. 🖼🖌",
    "Narrate a dramatic story about the last dream you had. 🌙📖",
    "Act out a well-known scene from a popular TV show. 📺🎭",
    "Meditate in a funny position for 1 minute. 🧘‍♂️😄",
    "Mix a drink with whatever ingredients people suggest. 🍹🍋",
    "What is your idea of a perfect date? 🌹",
    "Describe your dream romantic getaway. ✈️",
    "What's the most romantic gesture you've ever made for someone? 💖",
    "Have you ever been in love at first sight? 👀",
    "What's your favorite love song and why? 🎵",
    "Share a romantic movie that has deeply impacted you. 🎬",
    "Have you ever written a love letter? ✉️", "Describe your perfect kiss. 💋",
    "Who was your first crush and what attracted you to them? 💘",
    "What's your idea of the perfect romantic evening? 🌙",
    "Have you ever had a secret admirer? 💌",
    "What is your favorite memory with a past partner? 📆",
    "Name a celebrity couple you admire and why. 👫",
    "If you could go on a romantic date anywhere in the world, where would it be? 🗺",
    "Have you ever been serenaded or serenaded someone? 🎶",
    "Share a romantic tradition you'd like to start with a partner. 🕯",
    "What's your ultimate romantic fantasy? 🔥",
    "Describe your most memorable kiss. 💏",
    "Have you ever experienced love at the wrong time or place? ⌛️",
    "What's your favorite romantic gesture to receive? 🎁",
    "Share a romantic quote that resonates with you. 💬",
    "What's your love language - words of affirmation, acts of service, receiving gifts, quality time, or physical touch? 💬🎁⏰👩‍❤️‍👨",
    "Describe your ideal proposal scenario. 💍",
    "What's your outlook on public displays of affection? 🙈",
    "Have you ever been surprised with a romantic gesture, and what was it? 🎈",
    "Name a romantic book that has left a lasting impression on you. 📚",
    "What's the most romantic meal you've ever had? 🍽",
    "If you could experience a fictional love story, which one would it be and why? 💓",
    "What's your favorite thing about falling in love? 🥰",
    "Describe the most romantic setting you've ever been in. 🏞",
    "Share an intimate piece of artwork or poem that speaks to your romantic side. 🖼📝",
    "Describe the feeling of butterflies in your stomach when you're in love. 🦋",
    "Have you ever danced under the stars with someone you love? 💃🕺",
    "What's your idea of the perfect romantic gift? 🎁",
    "Have you ever written a poem or song about love? 🎶📝",
    "Share an unforgettable romantic moment you've experienced. 🌠",
    "What's your favorite romantic tradition from a different culture? 🌍",
    "Have you ever stargazed with a loved one? 🌌",
    "If you could relive a romantic memory, which one would it be? ↩️",
    "What's the most thoughtful surprise you've planned for someone you love? 🎁",
    "Share a meaningful love-related lesson you've learned. 📚",
    "What are your thoughts on long-distance relationships? 🌎",
    "Describe your ideal way to spend Valentine's Day. 💝",
    "Have you ever had a profound romantic experience while traveling? 🌍",
    "What's your favorite romantic line from a movie or book? 🎬📖",
    "Share a romantic gesture you've always wanted to experience. 🌷",
    "Describe a romantic moment from your favorite childhood memory. 🧸",
    "Have you ever received a love note or written one to someone? 📝",
    "What's the most unexpected romantic encounter you've had? 🎉",
    "If you could create your own romantic holiday, how would you celebrate it? 🎉"
]
